version: '2'
services:
  automatron:
    build: .
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - ./config:/config
      - ./plugins:/plugins
      - ./templates:/templates
      - ./static:/static
    depends_on:
      - redis
  redis:
    image: redis
  test:
    build: .
    command: python /tests.py -i -f
    depends_on:
      - redis
      - automatron
  mkdocs:
    build:
      context: .
      dockerfile: docs/Dockerfile
    volumes:
      - ./:/tmp/mkdocs
    ports:
      - 8080:8080
    command: mkdocs serve -a 0.0.0.0:8080
  coverage:
    build: .
    command: coverage run tests.py && coverage report
