version: '2'
services:
  automatron:
    build: .
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - ./config:/config
      - ./plugins:/plugins
    depends_on:
      - redis
  redis:
    image: redis
