site_name: Automatron
site_url: https://automatron.io
repo_url: https://github.com/madflojo/automatron
docs_dir: docs
site_dir: site
site_description: A framework for creating self-healing infrastructure. It simply detects system events & takes action.
site_author: Benjamin Cane
site_favicon: img/favicon.ico
theme: material
extra:
  logo: 'img/automatron.png'
  social:
    - type: twitter
      link: 'https://twitter.com/automatronio'
    - type: github
      link: 'https://github.com/madflojo/automatron'
markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true


pages:
  - Introduction: index.md
  - Installation:
    - Basic Installation: install/index.md
    - Deploy with Docker: install/docker.md
  - Configuration: configure.md
  - Runbooks:
    - Basics: runbooks/index.md
    - Checks: runbooks/checks.md
    - Actions: runbooks/actions.md
  - Facts: facts.md
  - Plugins:
    - Index: plugins/index.md
    - Discovery:
      - AWS: plugins/discovery/aws.md
      - Digital Ocean: plugins/discovery/digitalocean.md
      - Linode: plugins/discovery/linode.md
      - Network Map (nmap): plugins/discovery/nmap.md
      - Roster file: plugins/discovery/roster.md
      - Web Ping: plugins/discovery/webping.md
    - Checks:
      - Network:
        - Ping: plugins/checks/network/ping.md
        - TCP Connection: plugins/checks/network/tcp_connect.md
      - MySQL:
        - Available: plugins/checks/mysql/available.md
        - Status Metrics: plugins/checks/mysql/status_metrics.md
      - Systems:
        - Disk Free: plugins/checks/systems/disk_free.md
        - Memory Free: plugins/checks/systems/mem_free.md
    - Actions:
      - CloudFlare:
        - DNS: plugins/actions/cloudflare/dns.md
      - Docker:
        - Clean: plugins/actions/docker/clean.md
      - Systems:
        - Services: plugins/actions/systems/services.md
    - Vetting:
      - On Target:
        - Services: plugins/vetting/ontarget/services.md
        - System Info: plugins/vetting/ontarget/system-info.md
      - Remote:
        - Ping: plugins/vetting/remote/ping.md
#  - Customizing
#    - Actions
#    - Checks
#    - Datastores
#    - Discovery
#    - Logging
#    - Vetting
