site_name: Automatron
site_url: https://automatron.io
repo_url: https://github.com/madflojo/automatron
docs_dir: docs
site_dir: site
site_description: A framework for creating self-healing infrastructure. It simply detects system events & takes action.
site_author: Benjamin Cane
site_favicon: img/favicon.ico
theme: material
extra:
  logo: 'img/automatron.png'
  social:
    - type: twitter
      link: 'https://twitter.com/automatronio'
    - type: github
      link: 'https://github.com/madflojo/automatron'
markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true
pages:
  - Introduction: index.md
  - Installation:
    - Basic Installation: install/index.md
    - Deploy with Docker: install/docker.md
  - Configuration: configure.md
  - Runbooks:
    - Basics: runbooks/index.md
    - Checks: runbooks/checks.md
    - Actions: runbooks/actions.md
  - Facts: facts.md
  - Customizing:
    - Checks: plugins/checks.md
    - Actions: plugins/actions.md
    - Discovery: plugins/discovery.md
    - Vetting: plugins/vetting.md
