name: Verify Docker is running
schedule: "* * * * *"
checks:
  docker_running:
    execute_from: ontarget
    type: cmd
    cmd: service docker status
actions:
  restart_docker:
    execute_from: ontarget
    trigger: 2 # Restart after second occurance
    frequency: 300 # Run only once every 5 minutes
    call_on:
      - WARNING
      - CRITICAL
      - UNKNOWN
    type: cmd
    cmd: service docker restart
