logging: # Logging Configurations
  plugins:
    console: True
    syslog:
      facility: local0

discovery: # Discovery Configurations
  plugins:
    ## Start web service for HTTP GET or POST requests
    #web_ping:
    #  plugin: webping.py
    #  args: --ip 0.0.0.0 --port 8001
    ## Use NMAP to find new hosts
    nmap:
      target: 192.168.33.10/32
      flags: -sP
      interval: 40

datastore: # Datastore Configurations
  ## Default Datastore Engine
  engine: shelve
  ## Datastore Specific configuration
  plugins:
    ## Shelve
    shelve:
      filename: cache/runbook.db
## Redis 
#  redis:
#    db: 0
#    host: 127.0.0.1
#    port: 6379
