name: System Memory Usage
schedule: "* * * * *"
nodes:
  - "*"
checks:
  mem_free:
    # Check for the % of memory free create warning with 20% free and critical for 10% free
    execute_from: ontarget
    type: plugin
    plugin: systems/mem_free.py
    args: --warn=20 --critical=10
actions:
  capture_memusage:
    execute_from: ontarget
    trigger: 0
    frequency: 100
    call_on:
      - WARNING
      - CRITICAL
    type: cmd
    cmd: ps -eo rss,size,pid,ppid,cmd,user > /var/tmp/mem-usage-capture.out
{% if facts['ping'] == False %}
  ping:
    execute_from: remote
    trigger: 0
    frequency: 20
    call_on:
      - WARNING
      - CRITICAL
    type: cmd
    cmd: ping -c 1 127.0.0.1 >> /dev/stdout
{% endif %}
