name: System Memory Usage
schedule: "* * * * *"
nodes:
  - "*"
checks:
  mem_free:
    type: plugin
    plugin: systems/mem_free.py
    args: --threshold-perc=20
actions:
  capture_memusage:
    trigger: 0
    frequency: 100
    call_on:
      - WARNING
      - CRITICAL
    type: cmd
    cmd: ps -eo rss,size,pid,ppid,cmd,user > /var/tmp/mem-usage-capture.out
